### ISSUE TITLE
热加载如何配置？

### ISSUE THREAD

**Issue by biezhi** [yingzhuo/springboot-jetx2-examples#1]
[http://subchen.github.io/jetbrick-template/2x/config.html#-classpath-](http://subchen.github.io/jetbrick-template/2x/config.html#-classpath-)

我使用的是 `yml` 配置文件，下面是我的配置，好像不生效：

```yml
spring:
    jetbrick:
      template:
        enabled: true
        charset: UTF-8
        content-type: text/html
        prefix: templates/
        suffix: .html
        config:
          jetx.template.loaders: $loader
          $loader: jetbrick.template.loader.ClasspathResourceLoader
          $loader.reloadable: true
```
